name: Docker Build & Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vaishuk27
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=vaishuk27/vaishnavi-next-app:latest
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
